__default__:
    cpus-per-task : 4
    ntasks : 1
    mem-per-cpu : '2G'
    partition : "fast"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'
    job-name : '{rule}.{wildcards}'

rule_graph :
    output : 'logs/stdout/{rule}/dag.o'
    error : 'logs/error/{rule}/dag.e'

run_nanopolish :
    cpus-per-task : 8
    mem-per-cpu : '2G'
    partition : "long"

run_flye:
    cpus-per-task : 8
    mem-per-cpu : '2G'
    partition : "long"

run_canu:
    cpus-per-task : 16
    mem-per-cpu : '10G'
    partition : "long"

run_raven:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "long"

run_shasta:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "long"

run_smartdenovo:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "long"

run_miniasm:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "fast"

run_minipolish:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "fast"

run_circlator:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "fast"

run_racon:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "fast"

run_nanopolish:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "fast"

run_medaka_train:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "supermem"

run_medaka_consensus:
    cpus-per-task : 8
    mem-per-cpu : '4G'
    partition : "supermem"

run_kat:
    cpus-per-task : 1
    mem-per-cpu : '2G'
    partition : "long"
