__default__:
    cpus-per-task : 4
    ntasks : 1
    mem-per-cpu : '2'
    partition : "normal"
    output : 'logs/stdout/{rule}/{wildcards}'
    error : 'logs/error/{rule}/{wildcards}'

run_nanopolish :
    cpus-per-task : 8
    mem-per-cpu : '2'
    partition : "long"
 
run_flye:
    cpus-per-task : 8
    mem-per-cpu : '1'
    partition : "long"

run_canu:
    cpus-per-task : 8
    mem-per-cpu : '4'
    partition : "long"

run_raven:
    cpus-per-task : 8
    mem-per-cpu : '4'
    partition : "long"

run_shasta:
    cpus-per-task : 8
    mem-per-cpu : '4'
    partition : "long"

run_smartdenovo:
    cpus-per-task : 8
    mem-per-cpu : '4'
    partition : "long"

#run_miniasm:
#    cpus-per-task : 8
#    mem-per-cpu : '4'
#    partition : "normal"
#
#run_minipolish:
#    cpus-per-task : 8
#    mem-per-cpu : '4'
#    partition : "normal"
#
#run_circlator:
#    cpus-per-task : 8
#    mem-per-cpu : '4'
#    partition : "normal"
#
#run_racon:
#    cpus-per-task : 8
#    mem-per-cpu : '4'
#    partition : "normal"
#
#run_nanopolish:
#    cpus-per-task : 8
#    mem-per-cpu : '4'
#    partition : "normal"
#
run_medaka_train:
    cpus-per-task : 8
    mem-per-cpu : '4'
    partition : "supermem"

run_medaka_consensus:
    cpus-per-task : 8
    mem-per-cpu : '4'
    partition : "supermem"

run_kat:
    cpus-per-task : 1
    mem-per-cpu : '2'
    partition : "long"

