DATA:
    FASTQ: 'Data-Xoo-sub/fastq/'
    FAST5: 'Data-Xoo-sub/fast5/'
    ILLUMINA: 'Data-Xoo-sub/illumina/'
    GENOME_SIZE: '4.8m'
    REF: 'Data-Xoo-sub/ref/BAI3_Sanger.fsa'
    OUTPUT: 'output_xoo_sub_XXX3/'
    CIRCULAR: True

############ WC ################
ASSEMBLY:
    CANU : True
    FLYE : True
    MINIASM : True
    RAVEN : True
    SMARTDENOVO:  True
    SHASTA : True
CORRECTION:
    NANOPOLISH : True
    MEDAKA : True
#by default BUSCO is launched if True in QUALITY ASSEMBLY OR/ET POLISHING OR/ET CORRECTION step is/are activated
QUALITY:
    ASSEMBLY : False
    POLISHING : False
    CORRECTION : True
#### Others quality tools are lauched only in last assemblies
    WEESAM: True
    BLOBTOOLS: True
    ASSEMBLYTICS: True
    FIXSTART: True
#### Others quality softs but illumina reads are required
    KAT: True
#### Alignment of the various assemblies derived from a fastq file for small genomes (<10-20Mbp);
#### lauched only in last assemblies, only activate MAUVE if you have more that 1 sample
MSA:
    MAUVE: True


############ PARAMS ################
params:
    MINIMAP2:
        PRESET_OPTION: 'map-pb' # -x minimap2 preset option is map-pb by default (map-pb, map-ont etc)
    FLYE:
        OPTIONS: ''
    CANU:
        MAX_MEMORY: '15G'
        OPTIONS: '-fast'
    SMARTDENOVO:
        KMER_SIZE: 16
        OPTIONS: '-J 5000'
    SHASTA:
        MEM_MODE: 'filesystem'
        MEM_BACKING: 'disk'
    CIRCLATOR:
        OPTIONS: ''
    RACON:
        RACON_ROUNDS: 2 #1 to 9
    NANOPOLISH:
        # segment length to split assembly and correct it  default=50000
        NANOPOLISH_SEGMENT_LEN: '50000'
        # overlap length between segments  default=200
        NANOPOLISH_OVERLAP_LEN: '200'
        OPTIONS: ''
    MEDAKA:
        # if 'MEDAKA_TRAIN_WITH_REF' is True, medaka launchs training using reference found in DATA REF param. Medaka does not take in count other medaka model parameters below.
        MEDAKA_TRAIN_WITH_REF: False
        MEDAKA_MODEL_PATH: 'medakamodel/r941_min_high_g303_model.hdf5' # if empty this param is forgotten.
        #options to feature, train and consensus
        #
        MEDAKA_FEATURES_OPTIONS: '--batch_size 10 --chunk_len 100 --chunk_ovlp 10'
        #MEDAKA_FEATURES_OPTIONS: '--batch_size 100 --chunk_len 10000 --chunk_ovlp 1000'
        MEDAKA_TRAIN_OPTIONS: '--batch_size 10 --epochs 500 '
        #MEDAKA_TRAIN_OPTIONS: '--batch_size 100 --epochs 5000 '
        MEDAKA_CONSENSUS_OPTIONS: '-b 5 --hint=nomultithread' #use multithread on cluster
        #MEDAKA_CONSENSUS_OPTIONS: '-b 50 --hint=nomultithread' #use multithread on cluster
    BUSCO:
        DATABASE : 'Data-Xoo-sub/bacteria_odb10'
        MODEL : 'genome'
#        'SP' : 'caenorhabditis'
        SP : ''
    QUAST:
        REF: 'Data-Xoo-sub/ref/BAI3_Sanger.fsa'
        GFF: ''
        GENOME_SIZE_PB: 48000000
        #GENOME_SIZE_PB: 1000000
        OPTIONS : ''
    DIAMOND:
        DATABASE: 'Data-Xoo-sub/testBacteria.dmnd'
    MUMMER:
#         -l default 20
        MINMATCH : 100
#         -c default 65
        MINCLUSTER: 500
    ASSEMBLYTICS:
        UNIQUE_ANCHOR_LEN: 10000
        MIN_VARIANT_SIZE: 50
        MAX_VARIANT_SIZE: 10000

# cluster with scratch temporal repertory
SCRATCH : False

## @ BUILD SINGULARITY IMAGES PATH
tools:
## ASSEMBLERS:
    CANU_SIMG : '/path/to/singularity/images/canu-1.9.simg'
    FLYE_SIMG : '/path/to/singularity/images/flye-2.6.simg'
    MINIASM_SIMG : '/path/to/singularity/images/miniasm-0.3.simg'
    MINIPOLISH_SIMG : '/path/to/singularity/images/minipolish-0.1.2.simg'
## CIRCULARISATION
    CIRCLATOR_SIMG : '/path/to/singularity/images/circlator-1.5.5.simg'
## POLISHERS:
    RACON_SIMG : '/path/to/singularity/images/racon-1.4.3.simg'
    NANOPOLISH_SIMG : '/path/to/singularity/images/nanopolish-0.11.3.simg'
## CORRECTION
    MEDAKA_SIMG : '/path/to/singularity/images/medaka-gpu-1.0.3.simg'
## QUALITY
    BUSCO_SIMG : '/path/to/singularity/images/busco-4.0.4.simg'
    QUAST_SIMG : '/path/to/singularity/images/quast-5.0.2.simg'
    WEESAM_SIMG : '/path/to/singularity/images/weesam.simg'
    BLOBTOOLS_SIMG : '/path/to/singularity/images/bloobtools-v1.1.1.simg'
    MINIMAP2_SIMG: '/path/to/singularity/images/nanopolish-0.11.3.simg'
    DIAMOND_SIMG : '/path/to/singularity/images/diamond-0.9.30.simg'
    MUMMER_SIMG : '/path/to/singularity/images/mummer-4beta.simg'
    ASSEMBLYTICS_SIMG : '/path/to/singularity/images/assemblytics-1.2.simg'
    SAMTOOLS_SIMG : '/path/to/singularity/images/nanopolish-0.11.3.simg'
    KAT_SIMG : '/path/to/singularity/images/kat-2.4.2.simg'
    MINICONDA_SIMG : 'shub://vibaotram/singularity-container:cpu-guppy3.4-conda-api'
    R_SIMG: '/path/to/singularity/images/R.simg'


