## DATASET2 : to test everything  and particulary to test "canu", "medaka" and "weesam"
#
DATA:
    'FASTQ': 'Data-Xoo-sub/fastq/'
    'FAST5': 'Data-Xoo-sub/fast5/'
    'ILLUMINA' : 'Data-Xoo-sub/illumina/'
    'GENOME_SIZE': '4.8m'
    'REF': 'Data-Xoo-sub/ref/BAI3_Sanger.fsa'
    'OUTPUT': 'output_xoo_sub_circ/'
    'CIRCULAR' : True

############ WC ################
ASSEMBLY:
    CANU : True
    FLYE : True
    MINIASM : True
CORRECTION:
    NANOPOLISH : True
    MEDAKA : True
#by default BUSCO is launched if True in QUALITY ASSEMBLY OR/ET POLISHING OR/ET CORRECTION step is/are activated
QUALITY:
    ASSEMBLY : True
    POLISHING : True
    CORRECTION : True
#### Others quality tools are lauched only in last assemblies
    WEESAM: False
    BLOBTOOLS: True
    ASSEMBLYTICS: True
#### Others quality softs but illumina reads are required
    KAT: True

############ PARAMS ################
params:
    CANU:
        MAX_MEMORY: '15G'
        OPTIONS: '-fast'
    CIRCLATOR:
        OPTIONS: ''
    RACON:
        RACON_ROUNDS: 2 #1 to 9
    NANOPOLISH:
        # segment length to split assembly and correct it  default=50000
        NANOPOLISH_SEGMENT_LEN: '50000'
        # overlap length between segments  default=200
        NANOPOLISH_OVERLAP_LEN: '200'
    MEDAKA:
        # if 'MEDAKA_TRAIN_WITH_REF' is True, medaka launchs training using reference found in DATA REF param. Medaka does not take in count other medaka model parameters below.
        MEDAKA_TRAIN_WITH_REF: True
        MEDAKA_MODEL_PATH: 'medakamodel/r941_min_high_g303_model.hdf5' # if empty this param is forgotten.
    BUSCO:
        #DATABASE : '/home/comte/Documents/IPME/GTIPP/Nanopore/culebront_pipeline/bacteria_odb10/bacteria_odb10'
        DATABASE : '/scratch/orjuela/culebront_pipeline/bacteria_odb10'
        MODEL : 'genome'
#        'SP' : 'caenorhabditis'
        SP : ''
    QUAST:
        REF: 'Data-Xoo-sub/ref/BAI3_Sanger.fsa'
        #REF: 'TP-ONT/Clone1_DeepSimu/ref/reference.fasta'
        GFF: ''
        GENOME_SIZE_PB: 48000000
        #GENOME_SIZE_PB: 1000000
        OPTIONS : ''
    DIAMOND:
        DATABASE: '/scratch/orjuela/culebront_pipeline/testBacteria.dmnd'
#        'DATABASE': '/data/projects/banks/uniprot/reference_proteomes.dmnd'
    MUMMER:
#         -l default 20
        MINMATCH : 100
#         -c default 65
        MINCLUSTER: 500
    ASSEMBLYTICS:
        UNIQUE_ANCHOR_LEN: 10000
        MIN_VARIANT_SIZE: 50
        MAX_VARIANT_SIZE: 10000

## @ITROP PATH
tools:
## ASSEMBLERS:
    CANU_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/canu-1.9.simg'
    FLYE_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/Flye-2.6.simg'
    MINIASM_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/miniasm-0.3.simg'
## CIRCULARISATION
    CIRCLATOR_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/Circlator-1.5.5.simg'
## POLISHERS:
    RACON_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/racon-1.4.3.simg'
    NANOPOLISH_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/nanopolish-0.11.3.simg'
## CORRECTION
    MEDAKA_SIMG : '/data3/projects/containers/3.3.0/medaka-0.11.5.simg'
## QUALITY
    BUSCO_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/busco-4.0.5.simg'
    QUAST_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/quast-5.0.2.simg'
    WEESAM_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/weesam.simg'
    BLOBTOOLS_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/bloobtools-v1.1.1.simg'
    MINIMAP2_SIMG: '/scratch/orjuela/culebront_pipeline/Containers/nanopolish-0.11.3.simg'
    DIAMOND_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/Diamond-0.9.30.simg'
    MUMMER_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/mummer-4beta.simg'
    ASSEMBLYTICS_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/Assemblytics-1.2.simg'
    SAMTOOLS_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/nanopolish-0.11.3.simg'
    KAT_SIMG : '/scratch/orjuela/culebront_pipeline/Containers/KAT.simg'

