#snakemake -s Snakefile --configfile config.yaml --dag | dot -Tpdf > schema_pipeline_file.pdf
#snakemake -s Snakefile --configfile config.yaml --rulegraph | dot -Tpdf > schema_pipeline_global.pdf
#snakemake -s Snakefile --configfile config.yaml --dry-run

DATA:
    FASTQ: '/data3/projects/xanthopore/seb/culebron_run/in/fastq/'
    FAST5: '/data3/projects/xanthopore/seb/culebron_run/in/fast5/'
    ILLUMINA: ''
    GENOME_SIZE: '4.8m'
    REF: '/data3/projects/xanthopore/baotram/test_culebront/Ref/BAI3/BAI3_revcom_circular_final.fasta'
    OUTPUT: '/data3/projects/xanthopore/seb/culebron_run/outComplete'
    CIRCULAR: True

############ WC ################
ASSEMBLY:
    CANU : True
    FLYE : True
    MINIASM : True
CORRECTION:
    NANOPOLISH : True
    MEDAKA : True
#by default BUSCO is launched if True in QUALITY ASSEMBLY OR/ET POLISHING OR/ET CORRECTION step is/are activated
QUALITY:
    ASSEMBLY : True
    POLISHING : True
    CORRECTION : True
#### Others quality tools are lauched only in last assemblies
    WEESAM: True # Leave to false
    BLOBTOOLS: False
    ASSEMBLYTICS: False
#### Alignment of the various assemblies derived from a fastq file for small genomes (<10-20Mbp)
    MAUVE: True

#### Others quality softs but illumina reads are required
    KAT: False

############ PARAMS ################
params:
    CANU:
        MAX_MEMORY: '15G'
        OPTIONS: '-fast'
    CIRCLATOR:
        OPTIONS: '--assembler canu --data_type nanopore-corrected --merge_reassemble_end 2000 --merge_ref_end 60000 --b2r_length_cutoff 200000'
    RACON:
        RACON_ROUNDS: 2 #1 to 9
    NANOPOLISH:
        # segment length to split assembly and correct it  default=50000
        NANOPOLISH_SEGMENT_LEN: '50000'
        # overlap length between segments  default=200
        NANOPOLISH_OVERLAP_LEN: '200'
        #OPTIONS: ""
        OPTIONS: "--methylation-aware=dcm,dam --fix-homopolymers"
    MEDAKA:
        # if 'MEDAKA_TRAIN_WITH_REF' is True, medaka launchs training using reference found in DATA REF param. Medaka does not take in count other medaka model parameters below.
        MEDAKA_TRAIN_WITH_REF: False
        MEDAKA_MODEL_PATH: '/data3/projects/xanthopore/baotram/culebront_pipeline/r941_min_high_g330_model.hdf5' # if empty this param is forgotten.
    BUSCO:
        DATABASE : '/data3/projects/smrtlink/userdata/pacbacpipe/ancillaryData/xanthomonadales_odb10'
        MODEL : 'genome'
        SP : ''
    QUAST:
        REF: 'Data-Xoo-sub/ref/BAI3_Sanger.fsa'
        #REF: 'TP-ONT/Clone1_DeepSimu/ref/reference.fasta'
        GFF: ''
        GENOME_SIZE_PB: 48000000
        #GENOME_SIZE_PB: 1000000
        OPTIONS : ''
    DIAMOND:
        DATABASE: '/home/comte/Documents/IPME/GTIPP/Nanopore/culebront_pipeline/testBacteria.dmnd'
        #DATABASE: '/home/orjuela/Documents/tools/diamond_tool/database/testBacteria.dmnd'
        #DATABASE: '/scratch/orjuela/culebront_pipeline/testBacteria.dmnd'
#        'DATABASE': '/data/projects/banks/uniprot/reference_proteomes.dmnd'
    MUMMER:
#         -l default 20
        MINMATCH : 100
#         -c default 65
        MINCLUSTER: 500
    ASSEMBLYTICS:
        UNIQUE_ANCHOR_LEN: 10000
        MIN_VARIANT_SIZE: 50
        MAX_VARIANT_SIZE: 10000

tools:
###### ASSEMBLERS:
      CANU_SIMG: 'shub://SouthGreenPlatform/CulebrONT:canu-1.9.def'
      FLYE_SIMG: 'shub://SouthGreenPlatform/CulebrONT:flye-2.6.def'
      MINIASM_SIMG : 'shub://SouthGreenPlatform/CulebrONT:miniasm-0.3.def'
###### CIRCULARISATION
      CIRCLATOR_SIMG : 'shub://SouthGreenPlatform/CulebrONT:circlator-1.5.5.def'
###### POLISHERS:
      RACON_SIMG : 'shub://SouthGreenPlatform/CulebrONT:racon-1.4.3.def'
###### CORRECTION
      NANOPOLISH_SIMG : 'shub://SouthGreenPlatform/CulebrONT:nanopolish-0.11.3.def'
      #MEDAKA_SIMG : 'shub://SouthGreenPlatform/CulebrONT:medaka-gpu-0.11.5.def'
      MEDAKA_SIMG : 'shub://SouthGreenPlatform/CulebrONT:medaka-cpu-0.11.5.def'
###### QUALITY
      BUSCO_SIMG : 'shub://SouthGreenPlatform/CulebrONT:busco-4.def'
      QUAST_SIMG : 'shub://SouthGreenPlatform/CulebrONT:quality.def'
      WEESAM_SIMG : 'shub://SouthGreenPlatform/CulebrONT:quality.def'
      BLOBTOOLS_SIMG : 'shub://SouthGreenPlatform/CulebrONT:quality.def'
      DIAMOND_SIMG : 'shub://SouthGreenPlatform/CulebrONT:quality.def'
      MUMMER_SIMG : 'shub://SouthGreenPlatform/CulebrONT:mummer-4beta.def'
      ASSEMBLYTICS_SIMG : 'shub://SouthGreenPlatform/CulebrONT:quality.def'
      KAT_SIMG : 'shub://SouthGreenPlatform/CulebrONT:quality.def'
      MINICONDA_SIMG : 'shub://vibaotram/singularity-container:cpu-guppy3.4-conda-api'
      R_SIMG : '/data3/projects/containers/CULEBRONT/R.simg'
