__default__:
    cpus-per-task : 4
    ntasks : 10
    mem-per-cpu : 10G
    partition : "long"
    output : 'logs/stdout/{rule}/{wildcards}.o'
    error : 'logs/error/{rule}/{wildcards}.e'

run_nanopolish :
    cpus-per-task : 8
    mem-per-cpu : 8G
    partition : "long"

run_flye:
    cpus-per-task : 10
    mem-per-cpu : 15G
    partition : "long"

run_canu:
    cpus-per-task : 10
    ntasks : 10
    mem-per-cpu : 25G
    partition : "long"

run_raven:
    cpus-per-task : 8
    mem-per-cpu : 15G
    partition : "long"

run_shasta:
    cpus-per-task : 8
    mem-per-cpu : 20G
    partition : "long"

run_smartdenovo:
    cpus-per-task : 8
    mem-per-cpu : 15G
    partition : "long"

run_miniasm:
    cpus-per-task : 8
    mem-per-cpu : 15G
    partition : "long"

run_minipolish:
    cpus-per-task : 8
    mem-per-cpu : 15G
    partition : "long"

run_circlator:
    cpus-per-task : 8
    mem-per-cpu : 8G
    partition : "long"

run_racon:
    cpus-per-task : 8
    mem-per-cpu : 8G
    partition : "long"

run_nanopolish:
    cpus-per-task : 8
    mem-per-cpu : 8G
    partition : "long"

run_medaka_train:
    cpus-per-task : 8
    mem-per-cpu : 8G
    partition : "bigmem"

run_medaka_consensus:
    cpus-per-task : 8
    mem-per-cpu : 8G
    partition : "bigmem"

run_kat:
    cpus-per-task : 1
    mem-per-cpu : 8G
    partition : "long"
