$schema: "http://json-schema.org/draft-07/schema#"
description: an entry in the sample sheet
type: object
title: The Root Schema
required:
    - DATA
    - ASSEMBLY
    - CORRECTION
    - QUALITY
    - MSA
    - params
    - SCRATCH
    - tools
additionalProperties: false
properties:
    DATA:
        type: object
        required:
            - FASTQ
            - FAST5
            - ILLUMINA
            - GENOME_SIZE
            - REF
            - OUTPUT
            - CIRCULAR
        additionalProperties: false
        properties:
            FASTQ:
                type: string
                description: sample directory path
            FAST5:
                type: string
                description: fast5 directory path
            ILLUMINA:
                type: string
                description: illumina directory path
            GENOME_SIZE:
                type: string
                description: fast5 directory path
            REF:
                type: string
                description: reference file path / name
            OUTPUT:
                type: string
                description: output directory path
            CIRCULAR :
                type: boolean
                description: true if the genome is circular
    ASSEMBLY:
        type: object
        required:
            - CANU
            - FLYE
            - MINIASM
        additionalProperties: false
        properties:
            CANU :
                type: boolean
                description: true if you want to assemble the genome with canu
            FLYE :
                type: boolean
                description: true if you want to assemble the genome with flye
            MINIASM :
                type: boolean
                description: true if you want to assemble the genome with miniasm
    CORRECTION:
        type: object
        required:
            - NANOPOLISH
            - MEDAKA
        additionalProperties: false
        properties:
            NANOPOLISH :
                type: boolean
                description: true if you want to correct the genome with nanopolish
            MEDAKA :
                type: boolean
                description: true if you want to correct the genome with medaka
    QUALITY:
        type: object
        required:
            - ASSEMBLY
            - POLISHING
            - CORRECTION
            - WEESAM
            - BLOBTOOLS
            - ASSEMBLYTICS
            - KAT
        additionalProperties: false
        properties:
            ASSEMBLY :
                type: boolean
                description: true if you want to use the quality tools at the assembly step
            POLISHING :
                type: boolean
                description: true if you want to use the quality tools at the polishing step
            CORRECTION :
                type: boolean
                description: true if you want to use the quality tools at the correction step
            WEESAM:
                type: boolean
                description: true if you want to use weesam for quality
            BLOBTOOLS:
                type: boolean
                description: true if you want to use blobtools for quality
            ASSEMBLYTICS:
                type: boolean
                description: true if you want to use assemblytics for quality
            KAT:
                type: boolean
                description: true if you want to use kat for quality
    MSA:
        type: object
        required:
            - FIXSTART
            - MAUVE
        additionalProperties: false
        properties:
            FIXSTART:
                type: boolean
                description: true if you want to use fixstart for quality
            MAUVE:
                type: boolean
                description: true if you want to use mauve for quality
    params:
        type: object
        required:
            - MINIMAP2
            - CANU
            - CIRCLATOR
            - RACON
            - NANOPOLISH
            - MEDAKA
            - BUSCO
            - QUAST
            - DIAMOND
            - MUMMER
            - ASSEMBLYTICS
        additionalProperties: false
        properties:
            MINIMAP2:
                type: object
                additionalProperties: false
                properties:
                    PRESET_OPTION:
                        type: string
                        description: "preset option (-x) for minimap2"
            CANU:
                type: object
                additionalProperties: false
                properties:
                    MAX_MEMORY:
                        type: string
                        description: "preset option (-x) for minimap2"
                    OPTIONS:
                        type: string
                        description: "supplementary option for canu"
            CIRCLATOR:
                type: object
                additionalProperties: false
                properties:
                    OPTIONS:
                        type: string
                        description: "supplementary option for circlator"
            RACON:
                type: object
                additionalProperties: false
                required:
                    - RACON_ROUNDS
                properties:
                    RACON_ROUNDS:
                        type: integer
                        description: "number of rounds of racon for polishing"
            NANOPOLISH:
                type: object
                additionalProperties: false
                properties:
                    NANOPOLISH_SEGMENT_LEN:
                        type: string
                        description: "nanopolish segment lenght"
                    NANOPOLISH_OVERLAP_LEN:
                        type: string
                        description: "nanopolish overlap lenght"
                    OPTIONS:
                        type: string
                        description: "supplementary options for nanopolish"
            MEDAKA:
                type: object
                additionalProperties: false
                properties:
                    MEDAKA_TRAIN_WITH_REF:
                        type: boolean
                        description: "true if medaka should train"
                    MEDAKA_MODEL_PATH:
                        type: string
                        description: "medaka model path if no train"
            BUSCO:
                type: object
                additionalProperties: false
                required:
                    - DATABASE
                properties:
                    DATABASE :
                        type: string
                        description: "database path for busco"
                    MODEL :
                        type: string
                        description: "model type for busco"
                    SP :
                        type: string
                        description: "species specification for busco"
            QUAST:
                type: object
                additionalProperties: false
                required:
                    - REF
                properties:
                    REF:
                        type: string
                        description: "reference path for quast"
                    GFF:
                        type: string
                        description: "gff path for quast"
                    GENOME_SIZE_PB:
                        type: integer
                        description: "genome size for quast"
                    OPTIONS :
                        type: string
                        description: "suplementary options for quast"
            DIAMOND:
                type: object
                additionalProperties: false
                required:
                    - DATABASE
                properties:
                    DATABASE:
                      type: string
                      description: "database path for diamond"
            MUMMER:
                type: object
                additionalProperties: false
                properties:
                    MINMATCH :
                        type: integer
                        description: "number of missmatches for mummer"
                    MINCLUSTER:
                        type: integer
                        description: "min cluster for mummer"
            ASSEMBLYTICS:
                type: object
                additionalProperties: false
                properties:
                    UNIQUE_ANCHOR_LEN:
                        type: integer
                        description: "UNIQUE_ANCHOR_LEN for assemblytics"
                    MIN_VARIANT_SIZE:
                        type: integer
                        description: "MIN_VARIANT_SIZE for assemblytics"
                    MAX_VARIANT_SIZE:
                        type: integer
                        description: "MAX_VARIANT_SIZE for assemblytics"
    SCRATCH :
        type: boolean
        description: "true if scrach activated"
    tools:
        type: object
        additionalProperties: false
        required:
            - CANU_SIMG
            - FLYE_SIMG
            - MINIASM_SIMG
            - MINIPOLISH_SIMG
            - CIRCLATOR_SIMG
            - RACON_SIMG
            - NANOPOLISH_SIMG
            - MEDAKA_SIMG
            - BUSCO_SIMG
            - QUAST_SIMG
            - WEESAM_SIMG
            - BLOBTOOLS_SIMG
            - MINIMAP2_SIMG
            - DIAMOND_SIMG
            - MUMMER_SIMG
            - ASSEMBLYTICS_SIMG
            - SAMTOOLS_SIMG
            - KAT_SIMG
            - MINICONDA_SIMG
            - R_SIMG
        properties:
            'CANU_SIMG' :
                type: string
                description: "binary path for canu singularity"
            'FLYE_SIMG':
                type: string
                description: "binary path for flye singularity"
            'MINIASM_SIMG' :
                type: string
                description: "binary path for miniasm singularity"
            'MINIPOLISH_SIMG' :
                type: string
                description: "binary path for minipolish singularity"
            'CIRCLATOR_SIMG':
                type: string
                description: "binary path for circlator singularity"
            'RACON_SIMG' :
                type: string
                description: "binary path for racon singularity"
            'NANOPOLISH_SIMG' :
                type: string
                description: "binary path for racon singularity"
            'MEDAKA_SIMG' :
                type: string
                description: "binary path for medaka singularity"
            'BUSCO_SIMG' :
                type: string
                description: "binary path for busco singularity"
            'QUAST_SIMG':
                type: string
                description: "binary path for quast singularity"
            'WEESAM_SIMG' :
                type: string
                description: "binary path for weesam singularity"
            'BLOBTOOLS_SIMG' :
                type: string
                description: "binary path for blobtools singularity"
            'MINIMAP2_SIMG' :
                type: string
                description: "binary path for minimap2 singularity"
            'DIAMOND_SIMG' :
                type: string
                description: "binary path for diamond singularity"
            'MUMMER_SIMG' :
                type: string
                description: "binary path for mummer singularity"
            'ASSEMBLYTICS_SIMG' :
                type: string
                description: "binary path for assemblytics singularity"
            'SAMTOOLS_SIMG' :
                type: string
                description: "binary path for samtools singularity"
            'KAT_SIMG' :
                type: string
                description: "binary path for kat singularity"
            'MINICONDA_SIMG':
                type: string
                description: "binary path for miniconda singularity"
            'R_SIMG':
                type: string
                description: "binary path for R singularity"